"""remove email uniq

Revision ID: 38da07653d1f
Revises: e6fa56907583
Create Date: 2019-04-22 14:58:26.660931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38da07653d1f'
down_revision = 'e6fa56907583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    # ### end Alembic commands ###
